CREATE TABLE IF NOT EXISTS person (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR (100) NOT NULL
);

CREATE TABLE orders (
    id UUID NOT NULL PRIMARY KEY,
    customerId UUID NOT NULL REFERENCES person(id),
    duration SMALLINT NOT NULL,
    products UUID [] NOT NULL
);